import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Header from "../components/Header";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Link from "next/link";
import { useRef } from "react";

export default function Home() {
    const about = useRef<HTMLDivElement>();
    return (
        <div className={styles.main_container}>
            <Head>
                <title>Frontend Mentor | Minimalist Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon-32x32.png" />
            </Head>

            <Header />
            <main className={styles.main}>
                <picture>
                    <source
                        srcSet="/images/homepage/desktop/image-homepage-hero.jpg"
                        media="(min-width:1000px)"
                    />

                    <source
                        srcSet="/images/homepage/tablet/image-homepage-hero.jpg"
                        media="(min-width:600px)"
                    />
                    <img
                        src="/images/homepage/mobile/image-homepage-hero.jpg"
                        alt=""
                    />
                </picture>

                <div className={styles.main_info}>
                    <h1>
                        Hey, I’m Alex Spencer and I love building beautiful
                        websites
                    </h1>

                    <div className={styles.btn_wrap}>
                        <button
                            className={styles.btn_main}
                            type="button"
                            aria-label="button"
                            onClick={() => {
                                about.current.scrollIntoView();
                            }}
                        >
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                width="16"
                                height="14"
                            >
                                <g
                                    fill="none"
                                    fillRule="evenodd"
                                    stroke="#5FB4A2"
                                >
                                    <path d="M0 9l8 4 8-4" />
                                    <path opacity=".5" d="M0 5l8 4 8-4" />
                                    <path opacity=".25" d="M0 1l8 4 8-4" />
                                </g>
                            </svg>
                        </button>
                        <p>ABOUT ME</p>
                    </div>
                </div>
            </main>
            <section
                className={styles.section_aboutme}
                aria-label=" about me"
                ref={about}
            >
                <picture>
                    <source
                        srcSet="/images/homepage/desktop/image-homepage-profile.jpg"
                        media="(min-width:1000px)"
                    />
                    <source
                        srcSet="/images/homepage/tablet/image-homepage-profile.jpg"
                        media="(min-width:600px)"
                    />
                    <img
                        src="/images/homepage/mobile/image-homepage-profile.jpg"
                        alt=""
                    />
                </picture>
                <div className={styles.about_me}>
                    <h2> About Me</h2>
                    <p>
                        I’m a junior front-end developer looking for a new role
                        in an exciting company. I focus on writing accessible
                        HTML, using modern CSS practices and writing clean
                        JavaScript. When writing JavaScript code, I mostly use
                        React, but I can adapt to whatever tools are required.
                        I’m based in London, UK, but I’m happy working remotely
                        and have experience in remote teams. When I’m not
                        coding, you’ll find me outdoors. I love being out in
                        nature whether that’s going for a walk, run or cycling.
                        I’d love you to check out my work.
                    </p>
                    <Link href="/portfolio">
                        <a className={styles.button}>GO TO PORTFOLIO</a>
                    </Link>
                </div>
            </section>
            <Contact padding="home" />
            <Footer />
        </div>
    );
}
